## Assignment 1 - BA777

Note that this assignment captures topics from classes 3 & 4. You should run your queries in BigQuery Studio or a notebook (Colab Enterprise, BigQuery Studio, or Workbench) and submit the answers with your code in the rationale box of Blackboard (under the Assessment tab). 50% of the grade comes from the rationale and the other 50% from the multiple-choice answers.

### Question 1&2

Using the following table (`bigquery-public-data.baseball.schedules`), which baseball game had the biggest attendance in 2016?

In [1]:
%%bigquery
SELECT * FROM `bigquery-public-data.baseball.schedules` LIMIT 5

,gameId,gameNumber,seasonId,year,type,dayNight,duration,duration_minutes,homeTeamId,homeTeamName,awayTeamId,awayTeamName,startTime,attendance,status,created
0,e14b6493-9e7f-404f-840a-8a680cc364bf,1,565de4be-dc80-4849-a7e1-54bc79156cc8,2016,REG,D,3:07,187,03556285-bdbb-4576-a06d-42f71f46ddc5,Marlins,55714da8-fcaf-4574-8443-59bfb511a524,Cubs,2016-06-26 17:10:00+00:00,27318,closed,2016-10-06 06:25:15+00:00
1,1f32b347-cbcb-4c31-a145-0e685306d168,1,565de4be-dc80-4849-a7e1-54bc79156cc8,2016,REG,D,3:09,189,03556285-bdbb-4576-a06d-42f71f46ddc5,Marlins,55714da8-fcaf-4574-8443-59bfb511a524,Cubs,2016-06-25 20:10:00+00:00,29457,closed,2016-10-06 06:25:15+00:00
2,0c2292d1-7398-48be-bf8e-b41dad5e1a43,1,565de4be-dc80-4849-a7e1-54bc79156cc8,2016,REG,D,2:45,165,12079497-e414-450a-8bf2-29f91de646bf,Braves,55714da8-fcaf-4574-8443-59bfb511a524,Cubs,2016-06-11 20:10:00+00:00,43114,closed,2016-10-06 06:25:15+00:00
3,8fbec734-a15a-42ab-8d51-60790de7750b,1,565de4be-dc80-4849-a7e1-54bc79156cc8,2016,REG,D,3:42,222,12079497-e414-450a-8bf2-29f91de646bf,Braves,55714da8-fcaf-4574-8443-59bfb511a524,Cubs,2016-06-12 17:35:00+00:00,31625,closed,2016-10-06 06:25:15+00:00
4,89e514d5-fbf5-4b9d-bdac-6ca45bfd18dd,1,565de4be-dc80-4849-a7e1-54bc79156cc8,2016,REG,D,2:44,164,2142e1ba-3b40-445c-b8bb-f1f8b1054220,Phillies,55714da8-fcaf-4574-8443-59bfb511a524,Cubs,2016-06-08 17:05:00+00:00,28650,closed,2016-10-06 06:25:15+00:00

In [2]:
# Your answer goes here

### Question 3&4

In 2016, which team played the longest games at home on average?

Hint: You will need to take the average `duration_minutes` for each `homeTeamName`. This can be achieved by a `GROUP BY` and then an `ORDER BY`.

In [3]:
# Your answer goes here

---
---
The remaining questions refer to table `bigquery-public-data.austin_bikeshare.bikeshare_trips`.

**Important:** this table gets new trips every month. So that everyone gets the same answers, only use trips that started before August 1, 2026. Add this filter to every query from here on:

```sql
WHERE start_time < '2026-08-01'
```

In [4]:
%%bigquery
SELECT * FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips` LIMIT 5

,trip_id,subscriber_type,bike_id,bike_type,start_time,start_station_id,start_station_name,end_station_id,end_station_name,duration_minutes
0,28467234,Student Membership,21654,electric,2022-11-12 09:56:44+00:00,4051,10th/Red River,None,21st/Speedway @ PCL,9.0
1,28440932,Pay-as-you-ride,18923,electric,2022-11-09 09:57:57+00:00,4051,10th/Red River,None,23rd/San Jacinto @ DKR Stadium,7.0
2,28480824,Local365,21859,electric,2022-11-14 10:39:22+00:00,4051,10th/Red River,None,East 4th/Chicon,9.0
3,28509627,3-Day Weekender,21492,electric,2022-11-19 22:01:00+00:00,4051,10th/Red River,None,Rosewood/Chicon,6.0
4,28417265,Local31,19918,electric,2022-11-06 14:26:41+00:00,4051,10th/Red River,None,Rio Grande/12th,47.0

### Question 5&6

How many distinct and valid station IDs are in this table? Valid station IDs are integer numbers.

**Note1:** notice that we are looking for valid station IDs, meaning that any station ID that is missing (is null) should be excluded.

**Note2:** the question doesn't specify `start_station_id` or `end_station_id` and refers to all the station IDs. You would need to use a UNION to merge them all.

**Note3:** `start_station_id` is listed as INT but `end_station_id` is STR. To do a UNION, you must have all of the columns in the same format and the same data type. Convert `start_station_id` to STR: I.e, `CAST(start_station_id AS STRING)`

**Hint:** some records have `end_station_id` as `'Event'`. Since these do not qualify as valid station IDs we will have to exclude them.

In [5]:
# Your answer goes here

### Question 7&8
Which station has the highest number of trips that start from and end at that station?

In [6]:
# Your answer goes here

### Question 9&10
Which station is the most popular destination?

In [7]:
# Your answer goes here

### Question 11&12
How many different types of subscribers appear in this dataset?

In [8]:
# Your answer goes here

### Question 13&14
Which subscriber plan is the most popular?

In [9]:
# Your answer goes here

### Question 15&16
How many bike rides are in this dataset?

In [10]:
# Your answer goes here

### Question 17&18
Which month was the busiest in 2024?

Hint: Use the EXTRACT function to extract the date components. For more help, go to the documentation: https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions

In [11]:
# Your answer goes here